[project]
name = "nonebot-plugin-fuckyou"
version = "0.1.4"
description = "A NoneBot2 plugin designed for curse users"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = ["nonebot2>=2.0.0", "pydantic>=1.10.0,<2"]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc2333/nonebot-plugin-fuckyou"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
